# Claves
BINANCE_API_KEY=...
BINANCE_API_SECRET=...
TELEGRAM_BOT_TOKEN=...
TELEGRAM_CHAT_ID=...

# Universo y quotes
PREFERRED_QUOTES=USDT,USDC
SYMBOL_WHITELIST=BTC,ETH,SOL,BNB,LINK,TON,AVAX,XRP,ADA,DOGE
MIN_QUOTE_VOLUME=80000

# Estrategia conservadora
MIN_EUR_ORDER=20
TRADE_FRACTION=0.5
TAKE_PROFIT_MIN=0.012      # 1.2%
STOP_LOSS_MIN=-0.012       # -1.2%
ATR_TP_MULT=1.8
ATR_SL_MULT=1.4
ATR_TRAIL_MULT=1.0
TRAIL_PCT=0.005            # (acepta "0,005")

RSI_PERIOD=14
RSI_BUY_MIN=45
RSI_BUY_MAX=65
EMA_FAST=20
EMA_SLOW=50
ATR_PERIOD=14

# Ritmo / riesgo
COOLDOWN_PER_QUOTE_SEC=120
MAX_TRADES_PER_HOUR=8
DAILY_MAX_LOSS_EUR=30
MAX_HOLD_MIN=120
MAX_OPEN_POSITIONS=3

# Fees/slippage
COMMISSION_DEFAULT=0.001
SLIPPAGE_BUFFER_PCT=0.0005
NOTIONAL_BUFFER=1.03
MIN_QTY_BUFFER=1.0

# LLM (opcional; por defecto OFF)
LLM_ENABLED=false
OPENAI_API_KEY=
OPENAI_MODEL=gpt-4o-mini
OPENAI_BASE_URL=https://api.openai.com/v1

# Infra
TZ=Europe/Madrid
LOG_LEVEL=INFO
PORT=10000
